on: [push]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: glacier23/lab01website:${{ steps.short-sha.outputs.sha }}
          platforms: linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max