on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get the output time
        run: echo "work"
      - name: Trying to run docker
        run: docker ps

